
enum {
  MOV, LSL, ASR, ROR,
  AND, ANN, IOR, XOR,
  ADD, SUB, MUL, DIV,
  FAD, FSB, FML, FDV,
};

enum {
  LDR, LDB, STR, STB,
};

enum {
  BMI, BEQ, BCS, BVS,
  BLS, BLT, BLE, BR,
  BPL, BNE, BCC, BVC,
  BHI, BGE, BGT, NOP,
};

static const char * REGOPS = "MOVLSLASRRORANDANNIORXORADDSUBMULDIVFADFSBVMLFDV";
static const char * MOVOPS = "LDRLDBSTRSTB";
static const char * BRAOPS = "BMIBEQBCSBVSBLSBLTBLEBR BPLBNEBCCBVCBHIBGEBGTNOP";
